### PR TITLE
Fixes in support of Ecto 3, add index convenience methods

### PR DESCRIPTION
**Pull request by joeapearson**
@scottmessinger here's my latest set of changes to the mongodb repo.

It's a bit difficult to work on this without it becoming a can of worms.  In the immediate term I have:

* Added support for Erlang/OTP v24.
* Added some convenience methods for dealing with indexes
* Fixed the tests as far as I can
* Fixed a bunch of warnings as far as I can
* Fixed failures with MongoDb 4.x

My concerns:

* I'm not 100% certain of the fixes I've made that might touch TLS/SSL - these need to be tested and verified properly.  _Especially_ my replacement of the deprecated `^^^` operator with Bitwise.bxor.
* I haven't attempted to make this backwards compatible
* I haven't attempted to test this with any

Things I would like to do:

1. Give this repo the same treatment in terms of github actions so we can have some continuous validation.
2. Decide how far to go when it comes to backwards compatibility
3. Establish the best way of managing indexes for users.  Since these relate mostly to `mongodb_ecto` I will post back there.

Finally, I anticipate that I'm going to end up making more changes in this repo so you may wish to not accept this PR until things have settled down a bit.  If you spot any immediate problems please let me know.

Please let me know if there is anything else needed or desirable!

### CODE REVIEW

**Comment by scottmessinger** [comment]
Thanks!

> I'm not 100% certain of the fixes I've made that might touch TLS/SSL - these need to be tested and verified properly. Especially my replacement of the deprecated ^^^ operator with Bitwise.bxor.

Great question -- I know next to nothing about this layer. Maybe @ankhers could take a look -- he's the one that resolve the initial SSL issues with the driver. He went so far as to submit a patch to Erlang to make it work!

> I haven't attempted to make this backwards compatible
IMO, we should definitely make it backwards compatible to some version of Mongo. We're on 4, so, at a minimum I think we'd need to support that for entirely selfish reasons.


> Give this repo the same treatment in terms of github actions so we can have some continuous validation.
1000%

> Establish the best way of managing indexes for users. Since these relate mostly to mongodb_ecto I will post back there.

I have no idea about this -- I always manage the indexes by hand, but integrating with mongodb_ecto certainly makes sense.


> Please let me know if there is anything else needed or desirable!
Since you're doing work on this, it might be worth taking a look at https://github.com/zookzook/elixir-mongodb-driver @zookzook [hasn't been interested](https://github.com/zookzook/elixir-mongodb-driver/issues/36) in merging his work back into the upstream repo, but he has been very receptive to PRs and issues. Also, compatibility with Ecto hasn't been [something he's looked at](https://github.com/zookzook/elixir-mongodb-driver/issues/49) but I see no reason why the mongodb_ecto lib couldn't use his driver instead. 

Based on @zookzook's sustained work on the driver, I tend to think it would be the better long term driver for mongodb_ecto, but, at the same time, I have no idea how many breaking changes it has. Also, unless there's a way to resolve namespace issues in Elixir that I'm not aware of, both drivers can't be used in the same project due to zookzook's use of `Mongo` as the top level module. 

So, I have no idea what to do with that driver, but wanted to share my fuzzy, incomplete thinking on possibly using it instead of this driver for ecto.

**Comment by joeapearson** [comment]
Thanks @scottmessinger!  Unfortunately it seems like `mongodb_driver` has diverged from the original design of `mongodb` in a non-backwards compatible way, I guess because @zookzook had his own use cases.  There are some really nice things in `mongodb_driver` though I agree.  In my opinion it would be better for the community to merge these efforts one day.

For now I have found the easiest way forward to be to continue working on this driver.

**Comment by scottmessinger** [comment]
@joeapearson Great news! Justin Wood has transferred the repos to our new `elixir-mongo` organization, so you can create the PR against that repo. Thanks @ankhers!

**Comment by scottmessinger** [comment]
@joeapearson This looks good and it doesn't appear to have any breaking changes. Should we make a PR on the elixir-mongo repo and get this merged in? Let me know the status!

**Pull request closed without merging**
